"""Type stubs for yomail.exceptions."""

class ExtractionError(Exception):
    """Base exception for all extraction errors."""
    ...

class InvalidInputError(ExtractionError):
    """Input is not valid for processing.

    Raised when:
    - Input is empty or becomes empty after normalization
    - Input is not valid text
    """
    message: str
    def __init__(self, message: str) -> None: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class NoBodyDetectedError(ExtractionError):
    """No body content could be detected in the email."""
    message: str
    def __init__(self, message: str) -> None: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class LowConfidenceError(ExtractionError):
    """Extraction confidence is below the threshold.

    Attributes:
        message: Description of the error.
        confidence: The computed confidence score.
        threshold: The required threshold.
    """
    message: str
    confidence: float
    threshold: float
    def __init__(self, message: str, confidence: float, threshold: float) -> None: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
